// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/coletas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coletas">> = Specific
  const handler = {} as typeof import("../../src/app/coletas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configuracoes">> = Specific
  const handler = {} as typeof import("../../src/app/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/custos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/custos">> = Specific
  const handler = {} as typeof import("../../src/app/custos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/entregas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entregas">> = Specific
  const handler = {} as typeof import("../../src/app/entregas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/frota/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/frota">> = Specific
  const handler = {} as typeof import("../../src/app/frota/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/motoristas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/motoristas">> = Specific
  const handler = {} as typeof import("../../src/app/motoristas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacoes">> = Specific
  const handler = {} as typeof import("../../src/app/operacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pedidos">> = Specific
  const handler = {} as typeof import("../../src/app/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/relatorios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relatorios">> = Specific
  const handler = {} as typeof import("../../src/app/relatorios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rotas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rotas">> = Specific
  const handler = {} as typeof import("../../src/app/rotas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
