import {
  INDICATOR_CATEGORIES,
  type IndicatorDefinition,
} from '../types/indicator.types';

const RAW_CATALOG = [
  {
    key: 'operations_total',
    name: 'Total de operações',
    description: 'Quantidade total de operações planejadas dentro do período selecionado.',
    formula:
      'COUNT(operations.id) filtrando por companyId e intervalo planejado (plannedStartAt).',
    unit: 'count',
    betterWhen: 'higher',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'routeId', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'operations_total',
  },
  {
    key: 'operations_completed',
    name: 'Operações concluídas',
    description: 'Quantidade de operações finalizadas (status COMPLETED) no período.',
    formula:
      'COUNT(operations.id) com status COMPLETED e plannedStartAt dentro do intervalo.',
    unit: 'count',
    betterWhen: 'higher',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'routeId', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'operations_completed',
  },
  {
    key: 'operations_in_progress',
    name: 'Operações em andamento',
    description: 'Operações com status operacional ativo (pickup, trânsito ou entrega).',
    formula: 'COUNT(operations.id) com status em {IN_PICKUP, IN_TRANSIT, IN_DELIVERY}.',
    unit: 'count',
    betterWhen: 'lower',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'routeId'],
    granularities: ['realtime', 'day'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'operations_in_progress',
  },
  {
    key: 'operations_awaiting_planning',
    name: 'Aguardando planejamento',
    description: 'Operações criadas mas ainda sem plano aprovado.',
    formula: 'COUNT(operations.id) com status AWAITING_PLANNING.',
    unit: 'count',
    betterWhen: 'lower',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'routeId'],
    granularities: ['realtime', 'day'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'operations_awaiting_planning',
  },
  {
    key: 'operations_delayed',
    name: 'Operações atrasadas',
    description:
      'Operações cujo horário planejado de término já passou e ainda não foram concluídas.',
    formula:
      'COUNT(operations.id) onde plannedEndAt < NOW() e status não é COMPLETED/CANCELLED.',
    unit: 'count',
    betterWhen: 'lower',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'routeId'],
    granularities: ['realtime', 'day'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'operations_delayed',
  },
  {
    key: 'operations_completion_rate',
    name: 'Taxa de conclusão',
    description: 'Percentual de operações concluídas sobre o total do período.',
    formula: '(Operações concluídas / Operações totais) * 100.',
    unit: 'percentage',
    betterWhen: 'higher',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'routeId', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'operations_completion_rate',
  },
  {
    key: 'deliveries_completed',
    name: 'Entregas concluídas',
    description: 'Quantidade de entregas finalizadas no período solicitado.',
    formula: 'COUNT(deliveries.id) com status COMPLETED e completedAt no intervalo.',
    unit: 'count',
    betterWhen: 'higher',
    category: 'operation',
    dataSources: ['deliveries'],
    acceptedFilters: ['period', 'routeId', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'deliveries_completed',
  },
  {
    key: 'occurrences_open',
    name: 'Ocorrências abertas',
    description: 'Total de ocorrências ainda não resolvidas para a empresa.',
    formula: 'COUNT(operation_occurrences.id) com status = "open".',
    unit: 'count',
    betterWhen: 'lower',
    category: 'quality',
    dataSources: ['operation_occurrences'],
    acceptedFilters: ['period', 'routeId'],
    granularities: ['realtime', 'day'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'occurrences_open',
  },
  {
    key: 'vehicles_unavailable',
    name: 'Veículos indisponíveis',
    description: 'Veículos da frota fora de operação (status diferente de ativo).',
    formula: 'COUNT(vehicles.id) onde status != "active".',
    unit: 'count',
    betterWhen: 'lower',
    category: 'resources',
    dataSources: ['vehicles'],
    acceptedFilters: ['period'],
    granularities: ['realtime', 'day'],
    permissions: ['dashboard:read', 'frota:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'vehicles_unavailable',
  },
  {
    key: 'drivers_without_allocation',
    name: 'Motoristas sem alocação',
    description:
      'Motoristas ativos sem nenhuma operação atribuída nas janelas em execução.',
    formula:
      'COUNT(drivers.id active) - COUNT(DISTINCT operations.driverId) com status ativo.',
    unit: 'count',
    betterWhen: 'lower',
    category: 'resources',
    dataSources: ['drivers', 'operations'],
    acceptedFilters: ['period', 'routeId'],
    granularities: ['realtime', 'day'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'available',
    calculator: 'drivers_without_allocation',
  },
  // Planned indicators (metadata only)
  {
    key: 'on_time_delivery_rate',
    name: 'Entregas no prazo',
    description: 'Percentual de entregas concluídas até o horário combinado.',
    formula: 'COUNT(on_time) / COUNT(completed).',
    unit: 'percentage',
    betterWhen: 'higher',
    category: 'operation',
    dataSources: ['deliveries'],
    acceptedFilters: ['period', 'routeId', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'sla_rate',
    name: 'SLA de atendimento',
    description: 'Percentual de operações dentro do SLA formalizado por cliente.',
    formula: 'COUNT(com SLA cumprido) / COUNT(total).',
    unit: 'percentage',
    betterWhen: 'higher',
    category: 'operation',
    dataSources: ['operations', 'clients'],
    acceptedFilters: ['period', 'clientId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'avg_delivery_time',
    name: 'Tempo médio de entrega',
    description: 'Tempo médio em minutos entre início e conclusão da operação/entrega.',
    formula: 'AVG(actualEndAt - actualStartAt).',
    unit: 'duration',
    betterWhen: 'lower',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'routeId', 'driverId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'avg_stop_time',
    name: 'Tempo médio por parada',
    description: 'Tempo médio de atendimento nas paradas (operation_stops).',
    formula: 'AVG(serviceTimeMinutes).',
    unit: 'duration',
    betterWhen: 'lower',
    category: 'operation',
    dataSources: ['operation_stops'],
    acceptedFilters: ['period', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'redelivery_rate',
    name: 'Taxa de reentrega',
    description: 'Percentual de operações que exigiram nova tentativa de entrega.',
    formula: 'COUNT(reentregas) / COUNT(total).',
    unit: 'percentage',
    betterWhen: 'lower',
    category: 'quality',
    dataSources: ['deliveries'],
    acceptedFilters: ['period', 'clientId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'cancellation_rate',
    name: 'Taxa de cancelamento',
    description: 'Percentual de operações canceladas sobre o total planejado.',
    formula: 'COUNT(status = CANCELLED) / COUNT(total).',
    unit: 'percentage',
    betterWhen: 'lower',
    category: 'operation',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'vehicle_utilization',
    name: 'Utilização da frota',
    description: 'Percentual de veículos em uso versus frota total.',
    formula: 'DISTINCT operations.vehicleId / COUNT(vehicles).',
    unit: 'percentage',
    betterWhen: 'higher',
    category: 'resources',
    dataSources: ['vehicles', 'operations'],
    acceptedFilters: ['period', 'baseId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'frota:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'driver_utilization',
    name: 'Utilização de motoristas',
    description: 'Percentual de motoristas ativos alocados em operações.',
    formula: 'DISTINCT operations.driverId / COUNT(drivers ativos).',
    unit: 'percentage',
    betterWhen: 'higher',
    category: 'resources',
    dataSources: ['drivers', 'operations'],
    acceptedFilters: ['period', 'baseId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'downtime_rate',
    name: 'Tempo parado',
    description: 'Percentual de horas disponíveis não utilizadas por veículo.',
    formula: 'Horas paradas / Horas totais disponíveis.',
    unit: 'percentage',
    betterWhen: 'lower',
    category: 'resources',
    dataSources: ['vehicles', 'operations', 'maintenance'],
    acceptedFilters: ['period', 'vehicleId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'frota:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'quality_occurrences',
    name: 'Ocorrências registradas',
    description: 'Total de ocorrências registradas no período.',
    formula: 'COUNT(operation_occurrences.id).',
    unit: 'count',
    betterWhen: 'lower',
    category: 'quality',
    dataSources: ['operation_occurrences'],
    acceptedFilters: ['period', 'routeId', 'clientId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'critical_occurrences',
    name: 'Ocorrências críticas',
    description: 'Quantidade de ocorrências classificadas como críticas.',
    formula: 'COUNT(occurrences) where severity = CRITICAL.',
    unit: 'count',
    betterWhen: 'lower',
    category: 'quality',
    dataSources: ['operation_occurrences'],
    acceptedFilters: ['period', 'routeId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'delivery_failures',
    name: 'Falhas de entrega',
    description: 'Total de falhas (status FAILED) por motivo.',
    formula: 'COUNT(deliveries status FAILED).',
    unit: 'count',
    betterWhen: 'lower',
    category: 'quality',
    dataSources: ['deliveries'],
    acceptedFilters: ['period', 'clientId', 'routeId'],
    granularities: ['day', 'week', 'month'],
    permissions: ['dashboard:read', 'operations:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'cost_per_operation',
    name: 'Custo por operação',
    description: 'Custo médio das operações concluídas no período.',
    formula: 'SUM(actualCost) / COUNT(operations COMPLETED).',
    unit: 'currency',
    betterWhen: 'lower',
    category: 'financial',
    dataSources: ['operations', 'expenses'],
    acceptedFilters: ['period', 'clientId', 'routeId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'costs:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'cost_per_km',
    name: 'Custo por km',
    description: 'Custo médio por quilômetro rodado.',
    formula: 'SUM(actualCost) / SUM(actualDistanceKm).',
    unit: 'currency',
    betterWhen: 'lower',
    category: 'financial',
    dataSources: ['operations', 'fuel', 'expenses'],
    acceptedFilters: ['period', 'routeId', 'vehicleId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'costs:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'revenue',
    name: 'Receita',
    description: 'Receita bruta gerada pelas operações concluídas.',
    formula: 'SUM(freightValue) das operações concluídas.',
    unit: 'currency',
    betterWhen: 'higher',
    category: 'financial',
    dataSources: ['operations'],
    acceptedFilters: ['period', 'clientId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'finance:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'margin',
    name: 'Margem',
    description: 'Margem absoluta (receita - custo).',
    formula: 'SUM(freightValue) - SUM(actualCost).',
    unit: 'currency',
    betterWhen: 'higher',
    category: 'financial',
    dataSources: ['operations', 'expenses'],
    acceptedFilters: ['period', 'clientId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'finance:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'margin_rate',
    name: 'Margem percentual',
    description: 'Relação percentual entre margem e receita.',
    formula: '(Margem / Receita) * 100.',
    unit: 'percentage',
    betterWhen: 'higher',
    category: 'financial',
    dataSources: ['operations', 'expenses'],
    acceptedFilters: ['period', 'clientId'],
    granularities: ['week', 'month'],
    permissions: ['dashboard:read', 'finance:view'],
    formulaVersion: 1,
    status: 'planned',
  },
  {
    key: 'expenses_by_category',
    name: 'Despesas por categoria',
    description: 'Total de despesas agrupado por categoria contábil.',
    formula: 'SUM(expenses.amount) GROUP BY category.',
    unit: 'currency',
    betterWhen: 'lower',
    category: 'financial',
    dataSources: ['expenses'],
    acceptedFilters: ['period', 'baseId'],
    granularities: ['month'],
    permissions: ['dashboard:read', 'costs:view'],
    formulaVersion: 1,
    status: 'planned',
  },
] satisfies IndicatorDefinition[];

export const INDICATOR_CATALOG: IndicatorDefinition[] = [...RAW_CATALOG].sort(
  (a, b) => a.name.localeCompare(b.name),
);

export function findIndicatorDefinition(key: string) {
  return INDICATOR_CATALOG.find((indicator) => indicator.key === key);
}

export function listIndicatorCategories() {
  return INDICATOR_CATEGORIES;
}
